[package]
name = "kubera_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
kubera_core = { path = "../core" }
notify = "8"
pingora = { version = "0.5" }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "2"

[[bin]]
name = "kubera_gateway"
path = "src/main.rs"
