[package]
name = "kubera_gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = "0.8"
enumflags2 = { workspace = true }
clap = { workspace = true }
derive_builder = { workspace = true }
futures = { workspace = true }
getset = { workspace = true }
http = { workspace = true }
http-constant = { workspace = true }
itertools = { workspace = true }
kubera_core = { path = "../core" }
once_cell = "1"
pingora = { version = "0.5", features = ["pingora-proxy", "pingora-load-balancing", "lb", "rustls"] }
regex = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
unicase = { workspace = true }
url = "2"
prometheus = "0.14"

[dev-dependencies]
rstest = { workspace = true }

[[bin]]
name = "kubera_gateway"
path = "src/main.rs"
