[package]
name = "kubera_gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
derive_builder = { workspace = true }
futures = { workspace = true }
getset = { workspace = true }
hickory-resolver = "0.25"
http = { workspace = true }
http-constant = { workspace = true }
kubera_core = { path = "../core" }
once_cell = "1.21.3"
pingora = { version = "0.5", features = ["pingora-proxy", "pingora-load-balancing", "lb", "rustls"] }
regex = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
unicase = { workspace = true }
url = "2"

[[bin]]
name = "kubera_gateway"
path = "src/main.rs"
