[package]
name = "kubera_controlplane"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
derive_builder = "0.20"
futures = "0.3"
gateway-api = "0.15"
humantime-serde = "1"
k8s-openapi = { version = "0.24", features = ["v1_32"] }
kube = { version = "0.99", features = ["runtime", "derive"] }
kubera_core = { path = "../core" }
log = "0.4"
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
structured-logger = { version = "1" }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
getset = "0.1"
romap = "0.4"
flexi_logger = "0.30.2"
tracing = { version = "0.1", features = ["log"] }

[[bin]]
name = "kubera_controlplane"
path = "src/main.rs"
