apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "gateway_class.name" . }}
spec:
  controllerName: kubera.whitefamily.in/controlplane
  parametersRef:
    group: kubera.whitefamily.in
    kind: GatewayClassParameters
    name: {{ include "gateway_class.name" . }}

---
apiVersion: kubera.whitefamily.in/v1alpha1
kind: GatewayClassParameters
metadata:
  name: {{ include "gateway_class.name" . }}
spec:
  deployment:
    logLevel: {{ .Values.gateways.logLevel | default "Info" }}
    imagePullPolicy: {{ default .Values.gateways.deployment.imagePullPolicy .Values.deployments.imagePullPolicy "IfNotPresent" }}
    replicas: {{ .Values.gateways.deployment.replicas | default 1 }}
    {{- if .Values.gateways.deployment.strategy }}
    strategy:
    {{- toYaml .Values.gateways.deployment.strategy | nindent 6 -}}
    {{- end -}}
