apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kubera
spec:
  controllerName: whitefamily.in/kubera
  parametersRef:
    kind: GatewayClassParameters
    group: kubera.whitefamily.in
    name: kubera-gateway-class-config

---
apiVersion: kubera.whitefamily.in/v1alpha1
kind: GatewayClassParameters
metadata:
  name: kubera-gateway-class-config
spec: { }
