apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "gateway_class.name" . }}
spec:
  controllerName: vale-gateway.whitefamily.in/control-plane
  parametersRef:
    group: vale-gateway.whitefamily.in
    kind: GatewayClassParameters
    name: {{ include "gateway_class.name" . }}

---
apiVersion: vale-gateway.whitefamily.in/v1alpha1
kind: GatewayClassParameters
metadata:
  name: {{ include "gateway_class.name" . }}
spec:
  deployment:
    imagePullPolicy: {{ default .Values.gateways.deployment.imagePullPolicy .Values.deployments.imagePullPolicy "IfNotPresent" }}
    replicas: {{ .Values.gateways.deployment.replicas | default 2 }}
    {{- if .Values.gateways.deployment.strategy }}
    strategy:
    {{- toYaml .Values.gateways.deployment.strategy | nindent 6 -}}
    {{- end }}
    image:
      repository: {{ .Values.gateways.deployment.image.repository | default .Values.deployments.image.repository | default "vale-gateway" }}
      tag: {{ .Values.gateways.deployment.image.tag | default .Values.deployments.image.tag | default "latest" }}
  gateway:
    logLevel: {{ .Values.gateways.logLevel | default "Info" }}
    instrumentation:
      openTelemetry:
        exporter:
          endpoint: {{ .Values.gateways.instrumentation.openTelemetry.exporter.endpoint | default .Values.instrumentation.openTelemetry.exporter.endpoint | default "http://$(OTEL_COLLECTOR_NAME):4318" }}
        collector:
          name: {{ .Values.gateways.instrumentation.openTelemetry.collector.name | default .Values.instrumentation.openTelemetry.collector.name }}
    errorResponses:
      kind: ProblemDetail
