[package]
name = "kubera_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
kube = { version = "0.99.0", features = ["derive"] }
schemars = { version = "0.8" }
serde_json = "1.0"
gateway-api = "0.15.0"
k8s-openapi = "0.24.0"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
kube = { version = "0.99.0", features = ["derive"] }
gateway-api = { version = "0.15.0" }
k8s-openapi = { version = "0.24.0", features = ["v1_32"] }
schemars = { version = "0.8" }
serde_json = "1.0"
serde_yaml = "0.9"

[lib]
name = "kubera_core"
path = "src/lib.rs"