apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "controlPlane.name" . }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "services", "configmaps" ]
    verbs: [ "get", "watch", "list", "create", "update", "patch", "delete" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "watch", "list", "create", "update", "patch", "delete" ]
  - apiGroups: [ "", "gateway.networking.k8s.io", "discovery.k8s.io", "vale-gateway.whitefamily.in" ]
    resources: [ "*" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "gateway.networking.k8s.io" ]
    resources: [ "gatewayclasses/status", "gateways/status", "httproutes/status", "tcproutes/status", "udproutes/status" ]
    verbs: [ "get", "update", "patch" ]
  - apiGroups: [ "vale-gateway.whitefamily.in" ]
    resources: [ "staticresponsefilter/status" ]
    verbs: [ "get", "update", "patch" ]