apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: kubera-gateway
  namespace: default
spec:
  gatewayClassName: kubera-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: default
spec:
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ealen/echo-server:latest
          ports:
            - containerPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo-route
  namespace: default
spec:
  parentRefs:
    - name: kubera-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /echo
      backendRefs:
        - name: echo-service
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /foo
      backendRefs:
        - name: echo-service
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /bar
      backendRefs:
        - name: echo-service
          port: 80

