apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: kubera-gateway
  namespace: default
spec:
  gatewayClassName: kubera-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: default
spec:
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ealen/echo-server:latest
          ports:
            - containerPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
  namespace: default
spec:
  parentRefs:
    - name: kubera-gateway
  rules:
    # Basic echo route with both request and response header modifications
    - matches:
        - path:
            type: PathPrefix
            value: /echo
      filters:
        # Modify incoming request headers
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: "X-Gateway"
                value: "kubera-gateway"
              - name: "X-Route-Name"
                value: "echo-route"
            add:
              - name: "X-Request-ID"
                value: "generated-uuid-12345"
              - name: "X-Trace-Context"
                value: "gateway-processing"
            remove:
              - "X-Debug-Info"
              - "X-Internal-Header"
        # Modify outgoing response headers
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: "X-Powered-By"
                value: "Kubera Gateway"
              - name: "X-Response-Source"
                value: "echo-service"
            add:
              - name: "X-Gateway-Processing"
                value: "completed"
              - name: "X-Cache-Control"
                value: "no-cache"
            remove:
              - "X-Internal-Response"
              - "Server"
      backendRefs:
        - name: echo-service
          port: 80

    # API route with comprehensive header modifications
    - matches:
        - path:
            type: PathPrefix
            value: /api
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: "X-API-Version"
                value: "v1"
            add:
              - name: "X-Request-Source"
                value: "kubera-gateway"
      backendRefs:
        - name: echo-service
          port: 80

    # URL Rewrite example - rewrite internal API calls
    - matches:
        - path:
            type: PathPrefix
            value: /v1
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname: "internal-api-service"
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/api/v2"
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: "X-Rewritten-By"
                value: "kubera-gateway"
            add:
              - name: "X-Original-Path"
                value: "/v1"
      backendRefs:
        - name: echo-service
          port: 80

    # URL Rewrite with full path replacement
    - matches:
        - path:
            type: PathPrefix
            value: /legacy-service
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname: "new-backend.internal"
            path:
              type: ReplaceFullPath
              replaceFullPath: "/modern/api/endpoint"
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: "X-Legacy-Migration"
                value: "active"
      backendRefs:
        - name: echo-service
          port: 80

    # Redirect old paths to new locations
    - matches:
        - path:
            type: PathPrefix
            value: /old-api
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: api.example.com
            path:
              type: ReplaceFullPath
              replaceFullPath: /v2/api
            statusCode: 301

    # Redirect HTTP to HTTPS
    - matches:
        - path:
            type: PathPrefix
            value: /secure
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            # Keep same hostname and path, just change scheme
            statusCode: 302

    # Redirect with custom port and path prefix replacement
    - matches:
        - path:
            type: PathPrefix
            value: /legacy
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: new-service.example.com
            port: 8443
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /v3
            statusCode: 302

    # Secure admin route with security headers
    - matches:
        - path:
            type: PathPrefix
            value: /admin
        - headers:
            - type: Exact
              name: "X-Admin-Token"
              value: "admin-secret"
      filters:
        # Request security headers
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: "X-Security-Level"
                value: "high"
              - name: "X-Audit-Log"
                value: "enabled"
            remove:
              - "X-Public-Cache"
        # Response security headers
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: "X-Frame-Options"
                value: "DENY"
              - name: "X-Content-Type-Options"
                value: "nosniff"
              - name: "Strict-Transport-Security"
                value: "max-age=31536000; includeSubDomains"
            add:
              - name: "X-XSS-Protection"
                value: "1; mode=block"
              - name: "X-Admin-Response"
                value: "secured"
            remove:
              - "X-Debug-Info"
              - "X-Internal-Admin"
      backendRefs:
        - name: echo-service
          port: 80

    # CORS-enabled route with appropriate headers
    - matches:
        - path:
            type: PathPrefix
            value: /cors
      filters:
        # Request processing for CORS
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: "X-CORS-Route"
                value: "enabled"
            add:
              - name: "X-Origin-Processing"
                value: "gateway"
        # CORS response headers
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: "Access-Control-Allow-Origin"
                value: "*"
              - name: "Access-Control-Allow-Methods"
                value: "GET, POST, PUT, DELETE, OPTIONS"
              - name: "Access-Control-Allow-Headers"
                value: "Content-Type, Authorization, X-Requested-With"
            add:
              - name: "Access-Control-Max-Age"
                value: "86400"
              - name: "X-CORS-Policy"
                value: "permissive"
      backendRefs:
        - name: echo-service
          port: 80

---
# ConfigMap documenting the header modification capabilities
apiVersion: v1
kind: ConfigMap
metadata:
  name: header-modifier-examples
  namespace: default
data:
  README.md: |
    # Kubera Gateway Header Modification Examples
    
    This demo showcases both RequestHeaderModifier and ResponseHeaderModifier
    capabilities in the Kubera Gateway implementation.
    
    ## Request Header Modifications
    
    Request headers are modified before sending requests to backend services:
    
    ```yaml
    filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          set:
            - name: "X-Gateway"
              value: "kubera-gateway"
          add:
            - name: "X-Request-ID"
              value: "generated-uuid-12345"
          remove:
            - "X-Debug-Info"
    ```
    
    ## Response Header Modifications
    
    Response headers are modified before sending responses back to clients:
    
    ```yaml
    filters:
      - type: ResponseHeaderModifier
        responseHeaderModifier:
          set:
            - name: "X-Powered-By"
              value: "Kubera Gateway"
          add:
            - name: "X-Gateway-Processing"
              value: "completed"
          remove:
            - "X-Internal-Response"
    ```
    
    ## Demo Routes
    
    ### 1. Basic Echo Route (/echo)
    
    - **Request**: Adds gateway identification and tracing headers
    - **Response**: Adds processing status and cache control headers
    
    ### 2. API Route (/api)
    
    - **Request**: Sets API-specific headers and processing metadata
    - **Response**: Ensures proper content-type and adds rate limiting info
    
    ### 3. Admin Route (/admin)
    
    - **Request**: Adds security audit headers
    - **Response**: Implements comprehensive security headers (HSTS, CSP, etc.)
    
    ### 4. CORS Route (/cors)
    
    - **Request**: Adds origin processing headers
    - **Response**: Implements full CORS policy headers
    
    ## Testing the Demo
    
    ```bash
    # Test basic echo with header modifications
    curl -H "Host: kubera-gateway" http://localhost/echo
    
    # Test API route with JSON content-type
    curl -H "Content-Type: application/json" \
         -H "Host: kubera-gateway" \
         http://localhost/api
    
    # Test admin route with authentication
    curl -H "X-Admin-Token: admin-secret" \
         -H "Host: kubera-gateway" \
         http://localhost/admin
    
    # Test CORS route
    curl -H "Origin: https://example.com" \
         -H "Host: kubera-gateway" \
         http://localhost/cors
    ```
    
    ## Header Modification Features
    
    - **set**: Replace or add headers with specific values
    - **add**: Append headers (supports multiple values per header name)
    - **remove**: Delete headers from requests/responses
    
    ## Use Cases
    
    ### Request Header Modifications
    
    1. **Authentication**: Add/modify authorization headers
    2. **Observability**: Add tracing and request ID headers
    3. **API Versioning**: Set version-specific headers
    4. **Security**: Remove client debug/internal headers
    
    ### Response Header Modifications
    
    1. **Security**: Add security headers (HSTS, CSP, X-Frame-Options)
    2. **CORS**: Implement cross-origin resource sharing policies
    3. **Caching**: Control client and proxy caching behavior
    4. **Branding**: Add gateway identification headers
    5. **API Management**: Add rate limiting and processing status headers

  implementation-status.md: |
    # Kubera Gateway Implementation Status
    
    ✅ **Request Header Filters**
    
    - Core types: RequestHeaderModifier, RequestHeaderModifierBuilder
    - Filter implementation: RequestHeaderFilter
    - Proxy integration: Applied in upstream_request_filter
    - Gateway API support: Full conversion from Gateway API HTTPRoute
    
    ✅ **Response Header Filters**
    
    - Core types: ResponseHeaderModifier, ResponseHeaderModifierBuilder
    - Filter implementation: ResponseHeaderFilter
    - Proxy integration: Applied in response_filter
    - Gateway API support: Ready for Gateway API HTTPRoute integration
    
    ## Testing Results
    
    All header modification tests pass:
    
    - Request header modification: ✅ 4/4 tests passing
    - Response header modification: ✅ 4/4 tests passing
    - Builder patterns: ✅ Validation and error handling working
    - Integration: ✅ Proxy applies filters correctly
    
    ## Architecture
    
    ```
    Client Request → Gateway → RequestHeaderModifier → Backend
                                      ↓
    Client ← ResponseHeaderModifier ← Gateway ← Backend Response  
    ```
    
    Both request and response header modifications are applied transparently
    and can be configured independently per route.
