[package]
name = "kubera_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
kubera_core = { path = "../core" }
pingora = { version = "0.4" }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "kubera_proxy"
path = "src/main.rs"