logLevel: Info

clusterName: minikube

deployments:
  imagePullPolicy: IfNotPresent
  # Global image configuration - serves as default for all components
  image:
    repository: vale-gateway
    tag: latest

instrumentation:
  openTelemetry:
    collector:
      name: signoz-otel-collector
    exporter:
      endpoint: http://signoz-otel-collector.signoz2.svc.cluster.local:4317

gatewayClass:
  name: ""

controlPlane:
  name: ""
  logLevel: ""
  deployment:
    imagePullPolicy: ""
    replicas: 2
    strategy:
      type: Recreate
    # Control plane specific image override (optional)
    # Uses same base image as gateways but can be versioned independently
    image:
      repository: ""  # Will default to global image.repository
      tag: ""         # Will default to global image.tag
  instrumentation:
    openTelemetry:
      collector:
        name: ""
      exporter:
        endpoint: ""
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "500m"
      memory: "256Mi"


gateways:
  logLevel: ""
  deployment:
    imagePullPolicy: ""
    replicas: 3
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    # Gateway specific image override (optional)
    # Uses same base image as control plane but can be versioned independently
    image:
      repository: ""  # Will default to global image.repository
      tag: ""         # Will default to global image.tag
  instrumentation:
    openTelemetry:
      collector:
        name: ""
      exporter:
        endpoint: ""



  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: { }
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: { }
