logLevel: warn

images:
  pullPolicy: Always

gatewayclass:
  name: ""

controlplane:
  name: ""
  logLevel: ""
  image:
    repository: kubera-controlplane
    pullPolicy: ""
    tag: latest
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "500m"
      memory: "256Mi"




  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: { }
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: { }


